# Generated by Django 5.2.6 on 2025-09-26 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminder',
            name='notified',
            field=models.BooleanField(default=False),
        ),
    ]
